company_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.http.response import HttpResponseRedirect

urlpatterns = [
    url(r'^$', lambda request: HttpResponseRedirect('/vacation')),
    url(r'^admin/', admin.site.urls),
    url(r'^vacation/', include("vacation.urls"))
]

vacation/urls.py
"""
Vacation application, URL configuration
"""

from django.conf.urls import url

from vacation import api
from vacation import views


app_name = 'vacation'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^schedule/$', views.schedule, name='schedule'),
    url(r'^api/signin/', api.signin, name='signin'),
    url(r'^api/register/', api.register, name='register'),
    url(r'^api/duration/', api.duration, name='duration'),
    url(r'^api/apply/', api.apply, name='apply'),
    url(r'^api/employee_vacations/', api.employee_vacations, name='employee_vacations')
]

vacation/models.py
"""
Vacation application, models.
"""

from django.contrib.auth.models import User
from django.db import models
from django.db.models import QuerySet
from math import ceil


class JsonSupportModel:
    """
    Abstract class to add support for json serialization
    """
    def to_dict(self):
        """
        Must be overridden to return a dictionary
        :return: dictionary representation of the object
        """
        raise NotImplementedError


class VacationModel(models.Model, JsonSupportModel):
    """
    Vacation Model with support for json serialization
    """
    date_from = models.DateField()
    date_to = models.DateField()
    description = models.CharField(max_length=100)
    duration = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def to_dict(self):
        return {
            'id': self.id,
            'date_from': self.date_from.strftime('%d-%m-%Y'),
            'date_to': self.date_to.strftime('%d-%m-%Y'),
            'description': self.description,
            'duration': self.duration
        }


class JqGridViewModel:
    """
    JqGridViewModel to be used with JqGrid, created in a generic way
    to support all JsonSupportModel objects
    """

    def __init__(self, query_set: QuerySet, page=1, rows_per_page=5):
        """
        Constructor
        :param query_set: the query set to use for the grid data
        :param page: the current page number to display
        :param rows_per_page: the number of rows per page
        """
        self._query_set = query_set
        self._records_count = self._query_set.count()
        self._rows_per_page = rows_per_page
        self._page = page

    def total_pages(self):
        return ceil(self._records_count / self._rows_per_page)

    def page(self):
        return self._page

    def records_count(self):
        return self._records_count

    def rows_array(self):
        begin = (self._page - 1) * self._rows_per_page
        end = begin + self._rows_per_page
        return [x.to_dict() for x in self._query_set[begin:end]]

vacation/forms.py
"""
Vacation application, Forms.
These forms are used in views as well as apis.
"""

from django import forms

from company_site import settings


class LoginForm(forms.Form):
    """
    Login form used in @vacation.views and @vacation.api.signin
    """
    user_name = forms.EmailField(max_length=30, widget=forms.EmailInput(
        attrs={'class': 'form-control',
               'data-validation': 'email required'
               }
    ))

    user_password = forms.CharField(max_length=20, widget=forms.PasswordInput(
        attrs={'class': 'form-control',
               'data-validation': 'length alphanumeric required',
               'data-validation-length': 'min8'
               }
    ))


class RegisterForm(forms.Form):
    """
    Registration form used in @vacation.views and @vacation.api.register
    """
    user_name = forms.EmailField(min_length=5, max_length=30, widget=forms.EmailInput(
        attrs={'class': 'form-control',
               'data-validation': 'email length required',
               'data-validation-length': '5-30'
               }
    ))

    user_password = forms.CharField(min_length=8, max_length=20, widget=forms.PasswordInput(
        attrs={'class': 'form-control',
               'data-validation': 'length alphanumeric required',
               'data-validation-length': '8-20'
               }
    ))

    user_fname = forms.CharField(min_length=3, max_length=20, widget=forms.TextInput(
        attrs={'class': 'form-control',
               'data-validation': 'length alphanumeric required',
               'data-validation-length': '3-20'
               }
    ))

    user_lname = forms.CharField(min_length=3, max_length=20, widget=forms.TextInput(
        attrs={'class': 'form-control',
               'data-validation': 'length alphanumeric required',
               'data-validation-length': '3-20'
               }
    ))


class ApplyToVacationForm(forms.Form):
    """
    Apply to vacation form, used in @vacation.views and @vacation.api.apply
    """
    date_from = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS, widget=forms.DateInput(
        attrs={
            'class': 'form-control',
            'data-validation': 'date required',
            'data-validation-format': 'dd-mm-yyyy'
        }
    ))

    date_to = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS, widget=forms.DateInput(
        attrs={
            'class': 'form-control',
            'data-validation': 'date required',
            'data-validation-format': 'dd-mm-yyyy'
        }
    ))

    description = forms.CharField(max_length=100, min_length=10, widget=forms.Textarea(
        attrs={
            'class': 'form-control',
            'data-validation': 'length alphanumeric required',
            'data-validation-allowing': "-_.;",
            'data-validation-length': '10-100'
        }
    ))


class VacationDuration(forms.Form):
    """
    Calculate vacation duration form, used in @vacation.api.duration
    """
    date_from = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS)
    date_to = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS)

vacation/views.py
"""
Vacation application, views
"""

from django.http.response import HttpResponseRedirect
from django.shortcuts import render

from vacation.forms import LoginForm, RegisterForm, ApplyToVacationForm


def index(request):
    login_form = LoginForm()
    register_form = RegisterForm()

    return render(request, 'vacation/login.html', {
        'login_form': login_form,
        'register_form': register_form
    })


def schedule(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/vacation')

    form = ApplyToVacationForm()
    return render(request, 'vacation/schedule.html', {'form': form})

templates/vacation/login.html
{% extends 'vacation/master.html' %}
{% block pagetitle %} Vacations {% endblock %}
{% block body_content %}
<script type="text/javascript">
$(document).ready(function () {
    $('#btn-login').click(function () {
        $.post('{% url 'vacation:signin' %}', $('#loginform').serialize(), function(data){
            if(data.status === 'ok') window.location.replace('{% url 'vacation:schedule' %}')
        }).fail(function () {
          alert("Please check all the fields");
        });;
    });


    $('#btn-signup').click(function () {
        $.post('{% url 'vacation:register' %} ', $('#signupform').serialize(), function(data){
            if(data.status === 'ok') window.location.replace('{% url 'vacation:schedule' %}')
        }).fail(function () {
          alert("Please check all the fields");
        });
    });


    $.validate({
      onError: function () {
          return false;
      },
      onSuccess: function () {
          return true;
      }
    });
})
</script>

<div class="container">
    <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <div class="panel panel-info">
            <div class="panel-heading">
                <div class="panel-title">Sign In</div>
                <div style="float:right; font-size: 80%; position: relative; top:-10px"><a href="#">Forgot password?</a>
                </div>
            </div>

            <div style="padding-top:30px" class="panel-body">

                <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>

                <form id="loginform" class="form-horizontal" role="form" method="POST" action="{% url 'vacation:signin' %}">
                    {% csrf_token %}
                    <div style="margin-bottom: 25px" class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        {{ login_form.user_name }}
                    </div>

                    <div style="margin-bottom: 25px" class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        {{ login_form.user_password }}
                    </div>

                    <div style="margin-top:10px" class="form-group">
                        <!-- Button -->

                        <div class="col-sm-12 controls">
                            <a  id="btn-login" href="#" class="btn btn-success">Login </a>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12 control">
                            <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%">
                                Don't have an account!
                                <a href="#" onClick="$('#loginbox').hide(); $('#signupbox').show()">
                                    Sign Up Here
                                </a>
                            </div>
                        </div>
                    </div>
                </form>


            </div>
        </div>
    </div>
    <div id="signupbox" style="display:none; margin-top:50px"
         class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <div class="panel panel-info">
            <div class="panel-heading">
                <div class="panel-title">Sign Up</div>
                <div style="float:right; font-size: 85%; position: relative; top:-10px">
                    <a id="signinlink" href="#"
                       onclick="$('#signupbox').hide(); $('#loginbox').show()">Sign In</a></div>
            </div>
            <div class="panel-body">
                <form id="signupform" class="form-horizontal" role="form" method="POST" action="{% url 'vacation:register' %}">
                    {% csrf_token %}
                    <div id="signupalert" style="display:none" class="alert alert-danger">
                        <p>Error:</p>
                        <span></span>
                    </div>


                    <div class="form-group">
                        <label for="email" class="col-md-3 control-label">Email</label>
                        <div class="col-md-9">

                            {{ register_form.user_name }}
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="firstname" class="col-md-3 control-label">First Name</label>
                        <div class="col-md-9">
                            {{ register_form.user_fname }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="lastname" class="col-md-3 control-label">Last Name</label>
                        <div class="col-md-9">
                            {{ register_form.user_lname }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="password" class="col-md-3 control-label">Password</label>
                        <div class="col-md-9">
                            {{ register_form.user_password }}
                        </div>
                    </div>

                    <div class="form-group">
                        <!-- Button -->
                        <div class="col-md-12">
                            <button id="btn-signup" type="button" class="btn btn-info"><i class="icon-hand-right"></i>
                                &nbsp Sign Up
                            </button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/vacation/master.html
{% load static %}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">

{% with bootstrap="bootstrap/bootstrap-3.3.7-dist" jquery="jquery/jquery-3.2.1.min.js" %}
{% with jquery_validator="jquery/jquery.form-validator.min.js" jquery_ui="jquery/jquery-ui-1.9.2"%}
<head>
    <title>My Site - {% block pagetitle %}{% endblock %}</title>
    <script type="application/javascript" src="{% static jquery %}"></script>
    <script type="application/javascript" src="{% static jquery_ui|add:'/js/jquery-ui.js' %}"></script>
    <script type="application/javascript" src="{% static jquery_validator %}"></script>
    <script type="application/javascript" src="{% static bootstrap|add:'/js/bootstrap.min.js' %}"></script>
    {% block head_js %}{% endblock %}
    <link rel="stylesheet" href="{% static jquery_ui|add:'/css/cupertino/jquery-ui.css' %}" />
    <link rel="stylesheet" href="{% static bootstrap|add:'/css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static bootstrap|add:'/css/bootstrap-theme.css' %}" />
    {% block head_css %}{% endblock %}
</head>
{% endwith %}
{% endwith %}
<body>
<nav class="navbar navbar-default">
    <div class="navbar-header">
        <a href="#" class="navbar-brand">Company Site</a>
    </div>
</nav>

<div id="content">
    {% block body_content %}{% endblock %}
</div>
</body>

</html>

templates/vacation/schedule.html
{% extends 'vacation/master.html' %}
{% load static %}
{% block pagetitle %} Vacations {% endblock %}


{% block head_js %}
    {% with jqGridDir="jqGrid/jqGrid-5.2.1" %}
        <script type="application/javascript" src="{% static jqGridDir|add:'/js/jquery.jqGrid.min.js' %}"></script>
        <script type="application/javascript" src="{% static jqGridDir|add:'/js/grid.locale-en.js' %}"></script>
    {% endwith %}
{% endblock %}
{% block head_css %}
    {% with jqGridDir="jqGrid/jqGrid-5.2.1" %}
        <link rel="stylesheet" type="text/css" media="screen" href="{% static jqGridDir|add:'/css/ui.jqgrid.css' %}"/>
    {% endwith %}
{% endblock %}


{% block body_content %}
    <script type="text/javascript">
        $(function () {
            var $date_controls = $("#{{ form.date_from.auto_id }}").add("#{{ form.date_to.auto_id }}");

            function show_duration() {
                $.post('{% url 'vacation:duration' %} ', $('#applyform').serialize(), function (data) {
                    if (data.status === 'ok') $('#duration').html(data.response.duration + ' day(s)');
                }).fail(function () {
                    $('#duration').html('<b class="error">Please check your dates</b>');
                });
            }

            $date_controls.datepicker({
                dateFormat: "dd-mm-yy"
            });

            $date_controls.on('validation', function (evt, valid) {
                $(this).attr("data-valid", valid);
                if ($($date_controls.get(0)).attr("data-valid") == "true" &&
                    $($date_controls.get(1)).attr("data-valid") == "true") {
                    show_duration();
                }
            });

            $.validate({
                onError: function () {
                    return false;
                },
                onSuccess: function () {
                    return true;
                }
            });

            $('#btn-apply').click(function () {
                $.post('{% url 'vacation:apply' %}', $('#applyform').serialize(), function (data) {
                    if (data.status === "ok") {
                        alert("Your vacation has been added.");
                        window.location.replace('{% url 'vacation:schedule' %}')
                    }
                }).fail(function () {
                    alert("Please check all the fields");
                });
            });
        });
    </script>
    <div class="container">

        <div id="apply"
             class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <div class="panel-title">Apply for vacation - {{ request.user.first_name }}</div>
                </div>
                <div class="panel-body">
                    <form id="applyform" class="form-horizontal" role="form" method="POST"
                          action="{% url 'vacation:apply' %}">
                        {% csrf_token %}


                        <div class="form-group">
                            <label for="date_from" class="col-md-3 control-label">From</label>
                            <div class="col-md-9">
                                {{ form.date_from }}
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="date_to" class="col-md-3 control-label">To</label>
                            <div class="col-md-9">
                                {{ form.date_to }}
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="duration" class="col-md-3 control-label">Duration</label>
                            <div class="col-md-9">
                                <label id="duration" class="form-control-static"></label>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="description" class="col-md-3 control-label">Description</label>
                            <div class="col-md-9">
                                {{ form.description }}
                            </div>
                        </div>

                        <div class="form-group">
                            <!-- Button -->
                            <div class="col-md-3 col-md-offset-9">
                                <button id="btn-apply" type="button" class="btn btn-info"><i
                                        class="icon-hand-right"></i>
                                    &nbsp Apply Now
                                </button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <script type="text/javascript">
            $(function () {
                var myGrid = $('#list');
                myGrid.jqGrid({
                    caption: "Vacations",
                    url: '{% url 'vacation:employee_vacations' %}',
                    datatype: "json",
                    contentType: "application/json; charset-utf-8",
                    mtype: 'GET',
                    jsonReader: {
                        root: "response.rows",
                        page: "response.page",
                        total: "response.total",
                        records: "response.records",
                        repeatitems: false
                    },
                    colNames: ['Vacation ID', 'From', 'Till', 'Days', 'Description'],
                    colModel: [
                        {name: 'id'},
                        {name: 'date_from'},
                        {name: 'date_to'},
                        {name: 'duration'},
                        {name: 'description'}
                    ],
                    rowNum: 3,
                    pager: '#pager'
                });
            });
        </script>
        <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <table id="list"></table>
            <div id="pager"></div>
        </div>
    </div>
{% endblock body_content %}